In [1]:
%tensorflow_version 1.x

TensorFlow 1.x selected.


In [2]:
import tensorflow as tf
import numpy as np
print(tf.__version__)

1.15.2


In [17]:
import scipy.signal as signal

# Take a 7x7 image as example
J = np.array([[1, 2, 3, 4, 5, 6, 7],
[8, 9, 10, 11, 12, 13, 14],
[15, 16, 17, 18, 19, 20, 21],
[22, 23, 24, 25, 26, 27, 28],
[29, 30, 31, 32, 33, 34, 35],
[36, 37, 38, 39, 40, 41, 42],
[43, 44, 45, 46, 47, 48, 49]],dtype='float')

In [18]:
filter = np.array([[0,-4,2],
          [1,3,-2],
          [-1,1,-1]],dtype='float')

# f = tf.nn.conv2d(input= J , filter=filter, strides=1, padding='SAME', use_cudnn_on_gpu=None, name=None)
# print(f)

filter = np.rot90(filter, 2) 
print (J.shape, filter.shape)
f = signal.convolve2d(J, filter, 'same')        
print(f)

(7, 7) (3, 3)
[[ -2.  -8.  -7.  -6.  -5.  -4.  28.]
 [  5.  -3.  -4.  -5.  -6.  -7.  28.]
 [ -2. -10. -11. -12. -13. -14.  28.]
 [ -9. -17. -18. -19. -20. -21.  28.]
 [-16. -24. -25. -26. -27. -28.  28.]
 [-23. -31. -32. -33. -34. -35.  28.]
 [-29.  13.  13.  13.  13.  13.  27.]]


In [19]:
f = signal.convolve2d(J, filter, 'valid') 
print(f)

[[ -3.  -4.  -5.  -6.  -7.]
 [-10. -11. -12. -13. -14.]
 [-17. -18. -19. -20. -21.]
 [-24. -25. -26. -27. -28.]
 [-31. -32. -33. -34. -35.]]


In [20]:
f = signal.convolve2d(J, filter, 'full') 
print(f)

[[  -1.   -1.   -2.   -3.   -4.   -5.   -6.    1.   -7.]
 [ -10.   -2.   -8.   -7.   -6.   -5.   -4.   28.   -7.]
 [ -29.    5.   -3.   -4.   -5.   -6.   -7.   28.   -7.]
 [ -36.   -2.  -10.  -11.  -12.  -13.  -14.   28.   -7.]
 [ -43.   -9.  -17.  -18.  -19.  -20.  -21.   28.   -7.]
 [ -50.  -16.  -24.  -25.  -26.  -27.  -28.   28.   -7.]
 [ -57.  -23.  -31.  -32.  -33.  -34.  -35.   28.   -7.]
 [ -14.  -29.   13.   13.   13.   13.   13.   27.   49.]
 [  86.  -84.  -86.  -88.  -90.  -92.  -94. -196.    0.]]


In [35]:
filter_mean = np.array([[1/9,1/9,1/9],
            [1/9,1/9,1/9],
            [1/9,1/9,1/9]])
filter_gaussian = 1/16 * np.array([[1,2,1],[2,4,2],[1,2,1]])
print(filter_gaussian)

[[ 0.  2.  3.  4.  5.  6.  0.]
 [ 2.  9. 10. 11. 12. 13.  7.]
 [ 9. 16. 17. 18. 19. 20. 14.]
 [16. 23. 24. 25. 26. 27. 21.]
 [23. 30. 31. 32. 33. 34. 28.]
 [30. 37. 38. 39. 40. 41. 35.]
 [ 0. 37. 38. 39. 40. 41.  0.]]
[[0.0625 0.125  0.0625]
 [0.125  0.25   0.125 ]
 [0.0625 0.125  0.0625]]


In [27]:
filter_mean = np.rot90(filter_mean, 2) 
print (J.shape, filter_mean.shape)
f = signal.convolve2d(J, filter_mean, 'same')        
print(f)

(7, 7) (3, 3)
[[ 2.22222222  3.66666667  4.33333333  5.          5.66666667  6.33333333
   4.44444444]
 [ 5.66666667  9.         10.         11.         12.         13.
   9.        ]
 [10.33333333 16.         17.         18.         19.         20.
  13.66666667]
 [15.         23.         24.         25.         26.         27.
  18.33333333]
 [19.66666667 30.         31.         32.         33.         34.
  23.        ]
 [24.33333333 37.         38.         39.         40.         41.
  27.66666667]
 [17.77777778 27.         27.66666667 28.33333333 29.         29.66666667
  20.        ]]


In [37]:
filter_median = signal.medfilt(J,kernel_size = 3)
print(filter_median)

[[ 0.  2.  3.  4.  5.  6.  0.]
 [ 2.  9. 10. 11. 12. 13.  7.]
 [ 9. 16. 17. 18. 19. 20. 14.]
 [16. 23. 24. 25. 26. 27. 21.]
 [23. 30. 31. 32. 33. 34. 28.]
 [30. 37. 38. 39. 40. 41. 35.]
 [ 0. 37. 38. 39. 40. 41.  0.]]


In [29]:
filter_gaussian = np.rot90(filter_gaussian, 2) 
print (J.shape, filter_gaussian.shape)
f = signal.convolve2d(J, filter_gaussian, 'same')        
print(f)

(7, 7) (3, 3)
[[ 2.0625  3.25    4.      4.75    5.5     6.25    5.0625]
 [ 6.25    9.     10.     11.     12.     13.     10.25  ]
 [11.5    16.     17.     18.     19.     20.     15.5   ]
 [16.75   23.     24.     25.     26.     27.     20.75  ]
 [22.     30.     31.     32.     33.     34.     26.    ]
 [27.25   37.     38.     39.     40.     41.     31.25  ]
 [23.0625 31.25   32.     32.75   33.5    34.25   26.0625]]
