In [1]:
import tensorflow as tf
import numpy as np
import scipy.signal as signal
import matplotlib.pyplot as plt

In [2]:
mp1=100 # 100 lines
np1=50 # each line with 30 points
noise1 = (2.0 * np.random.random((mp1,np1)) - 1) * 0.1
X_train1 = np.ones((mp1,np1)) + noise1
print(X_train1)

[[1.06238829 1.04428385 1.03169135 ... 0.91288777 1.00837196 0.94736441]
 [1.00908941 0.99493404 0.98884976 ... 1.00836053 1.04039667 1.03957358]
 [0.97232472 0.95279338 0.90487999 ... 0.92376001 1.0034295  0.90337939]
 ...
 [0.90425525 0.99133752 0.99909944 ... 1.06640986 0.95537703 1.07926594]
 [1.07193118 0.92389884 0.97995818 ... 1.03157787 1.05982599 1.07557637]
 [0.93758503 0.97867965 1.08032793 ... 0.9055999  0.97655356 0.96081744]]


In [3]:
X_train2 = np.ones((mp1, np1))
for row in X_train2:
    randnum = int(np.random.random(1) * 45 + 1) # the key point : )
    row[randnum] = 0.1
    row[randnum + 1] = 0.1
    row[randnum + 2] = 0.1
    row[randnum + 3] = 0.1
    row[randnum + 4] = 0.1

print(randnum)

X_train2 = X_train2 + noise1
print(X_train2)

10
[[1.06238829 1.04428385 1.03169135 ... 0.91288777 1.00837196 0.94736441]
 [1.00908941 0.99493404 0.98884976 ... 0.10836053 0.14039667 1.03957358]
 [0.97232472 0.95279338 0.90487999 ... 0.92376001 1.0034295  0.90337939]
 ...
 [0.90425525 0.99133752 0.99909944 ... 1.06640986 0.95537703 1.07926594]
 [1.07193118 0.92389884 0.97995818 ... 1.03157787 1.05982599 1.07557637]
 [0.93758503 0.97867965 1.08032793 ... 0.9055999  0.97655356 0.96081744]]


In [4]:
Y_train1 = np.zeros(mp1)[:,np.newaxis]
Y_train2 = np.ones(mp1)[:,np.newaxis]

X_train = np.concatenate((X_train1, X_train2), axis=0)
Y_train = np.concatenate((Y_train1, Y_train2), axis=0)
X_train = X_train -1
X_train = np.expand_dims(X_train, axis=2)

In [5]:
from keras.models import Sequential
from keras.layers import Dense, Activation, MaxPooling1D, GlobalAveragePooling1D, Conv1D

model = Sequential()
model.add(Conv1D(32, 3, activation='relu',input_shape=(np1, 1)))
model.add(MaxPooling1D(3))
model.add(Conv1D(16, 3, activation='relu'))
model.add(GlobalAveragePooling1D())
##model.add(Dropout(0.75))
model.add(Dense(1, activation='sigmoid'))

model.compile(loss='binary_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])

model.fit(X_train, Y_train, batch_size=32, epochs=10)
loss,accuracy = model.evaluate(X_train, Y_train,batch_size=32)
print ("test loss for testdata: {}".format(loss))
print ("test accuracy for testdata: {}".format(accuracy))

Epoch 1/10
7/7 [==============================] - 2s 6ms/step - loss: 0.6822 - accuracy: 0.5283
Epoch 2/10
7/7 [==============================] - 0s 3ms/step - loss: 0.6705 - accuracy: 0.5112
Epoch 3/10
7/7 [==============================] - 0s 3ms/step - loss: 0.6612 - accuracy: 0.5269
Epoch 4/10
7/7 [==============================] - 0s 3ms/step - loss: 0.6485 - accuracy: 0.9080
Epoch 5/10
7/7 [==============================] - 0s 3ms/step - loss: 0.6306 - accuracy: 0.9466
Epoch 6/10
7/7 [==============================] - 0s 3ms/step - loss: 0.6153 - accuracy: 0.9129
Epoch 7/10
7/7 [==============================] - 0s 3ms/step - loss: 0.5992 - accuracy: 0.9758
Epoch 8/10
7/7 [==============================] - 0s 3ms/step - loss: 0.5767 - accuracy: 0.9864
Epoch 9/10
7/7 [==============================] - 0s 3ms/step - loss: 0.5553 - accuracy: 0.9912
Epoch 10/10
7/7 [==============================] - 0s 2ms/step - loss: 0.5116 - accuracy: 1.0000
test loss for testdata: 0.5116003155708

In [6]:
from keras.models import Sequential
from keras.layers import Dense, Activation, MaxPooling1D, GlobalAveragePooling1D, Conv1D

model = Sequential()
model.add(Conv1D(32, 3, activation='relu',input_shape=(np1, 1)))
model.add(MaxPooling1D(3))
model.add(Conv1D(16, 3, activation='relu'))
model.add(GlobalAveragePooling1D())
##model.add(Dropout(0.75))
model.add(Dense(1, activation='sigmoid'))

model.compile(loss='binary_crossentropy',
              optimizer='rmsprop',
              metrics=['accuracy'])

model.fit(X_train, Y_train, batch_size=32, epochs=10)
loss,accuracy = model.evaluate(X_train, Y_train,batch_size=32)
print ("test loss for testdata: {}".format(loss))
print ("test accuracy for testdata: {}".format(accuracy))

Epoch 1/10
7/7 [==============================] - 1s 4ms/step - loss: 0.6831 - accuracy: 0.7986
Epoch 2/10
7/7 [==============================] - 0s 3ms/step - loss: 0.6543 - accuracy: 0.5504
Epoch 3/10
7/7 [==============================] - 0s 4ms/step - loss: 0.6444 - accuracy: 0.6267
Epoch 4/10
7/7 [==============================] - 0s 4ms/step - loss: 0.6173 - accuracy: 0.8049
Epoch 5/10
7/7 [==============================] - 0s 4ms/step - loss: 0.5993 - accuracy: 0.9410
Epoch 6/10
7/7 [==============================] - 0s 3ms/step - loss: 0.5781 - accuracy: 1.0000
Epoch 7/10
7/7 [==============================] - 0s 3ms/step - loss: 0.5489 - accuracy: 1.0000
Epoch 8/10
7/7 [==============================] - 0s 3ms/step - loss: 0.5270 - accuracy: 1.0000
Epoch 9/10
7/7 [==============================] - 0s 3ms/step - loss: 0.4992 - accuracy: 1.0000
Epoch 10/10
7/7 [==============================] - 0s 2ms/step - loss: 0.4468 - accuracy: 1.0000
test loss for testdata: 0.4467925131320

In [7]:
from keras.models import Sequential
from keras.layers import Dense, Activation, MaxPooling1D, GlobalAveragePooling1D, Conv1D

model = Sequential()
model.add(Conv1D(32, 3, activation='relu',input_shape=(np1, 1)))
model.add(MaxPooling1D(3))
model.add(Conv1D(16, 3, activation='sigmoid'))
model.add(GlobalAveragePooling1D())
##model.add(Dropout(0.75))
model.add(Dense(1, activation='sigmoid'))

model.compile(loss='binary_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])

model.fit(X_train, Y_train, batch_size=32, epochs=10)
loss,accuracy = model.evaluate(X_train, Y_train,batch_size=32)
print ("test loss for testdata: {}".format(loss))
print ("test accuracy for testdata: {}".format(accuracy))

Epoch 1/10
7/7 [==============================] - 0s 4ms/step - loss: 0.6939 - accuracy: 0.5176
Epoch 2/10
7/7 [==============================] - 0s 3ms/step - loss: 0.6902 - accuracy: 0.5025
Epoch 3/10
7/7 [==============================] - 0s 3ms/step - loss: 0.6864 - accuracy: 0.6762
Epoch 4/10
7/7 [==============================] - 0s 3ms/step - loss: 0.6828 - accuracy: 0.9670
Epoch 5/10
7/7 [==============================] - 0s 3ms/step - loss: 0.6785 - accuracy: 0.9720
Epoch 6/10
7/7 [==============================] - 0s 3ms/step - loss: 0.6738 - accuracy: 0.9776
Epoch 7/10
7/7 [==============================] - 0s 4ms/step - loss: 0.6690 - accuracy: 1.0000
Epoch 8/10
7/7 [==============================] - 0s 4ms/step - loss: 0.6629 - accuracy: 0.9963
Epoch 9/10
7/7 [==============================] - 0s 3ms/step - loss: 0.6559 - accuracy: 0.9973
Epoch 10/10
7/7 [==============================] - 0s 2ms/step - loss: 0.6431 - accuracy: 1.0000
test loss for testdata: 0.6431159973144

In [12]:
X_train3 = np.ones((50,1))
X_train3[2:5]=0.1
X_train3 = X_train3.T
X_train3 = X_train3 - 1
print(X_train3)

[[ 0.   0.  -0.9 -0.9 -0.9  0.   0.   0.   0.   0.   0.   0.   0.   0.
   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
   0.   0.   0.   0.   0.   0.   0.   0. ]]


In [14]:
from keras.models import Sequential
from keras.layers import Dense, Activation, MaxPooling1D, GlobalAveragePooling1D, Conv1D

model = Sequential()
model.add(Conv1D(32, 3, activation='relu',input_shape=(np1, 1)))
model.add(MaxPooling1D(3))
model.add(Conv1D(16, 3, activation='sigmoid'))
model.add(GlobalAveragePooling1D())
##model.add(Dropout(0.75))
model.add(Dense(1, activation='sigmoid'))

model.compile(loss='binary_crossentropy',
              optimizer='rmsprop',
              metrics=['accuracy'])

model.fit(X_train, Y_train, batch_size=32, epochs=10)
loss,accuracy = model.evaluate(X_train, Y_train,batch_size=32)
print ("test loss for testdata: {}".format(loss))
print ("test accuracy for testdata: {}".format(accuracy))
print(model.predict(X_train3))

Epoch 1/10
7/7 [==============================] - 1s 3ms/step - loss: 0.9210 - accuracy: 0.5136
Epoch 2/10
7/7 [==============================] - 0s 3ms/step - loss: 0.9268 - accuracy: 0.4766
Epoch 3/10
7/7 [==============================] - 0s 3ms/step - loss: 0.9176 - accuracy: 0.4557
Epoch 4/10
7/7 [==============================] - 0s 3ms/step - loss: 0.7864 - accuracy: 0.5395
Epoch 5/10
7/7 [==============================] - 0s 3ms/step - loss: 0.7966 - accuracy: 0.5034
Epoch 6/10
7/7 [==============================] - 0s 3ms/step - loss: 0.7439 - accuracy: 0.5315
Epoch 7/10
7/7 [==============================] - 0s 4ms/step - loss: 0.7461 - accuracy: 0.4973
Epoch 8/10
7/7 [==============================] - 0s 3ms/step - loss: 0.7216 - accuracy: 0.4982
Epoch 9/10
7/7 [==============================] - 0s 3ms/step - loss: 0.7175 - accuracy: 0.4710
Epoch 10/10
7/7 [==============================] - 0s 2ms/step - loss: 0.6630 - accuracy: 0.5000
test loss for testdata: 0.6630459427833