# HW1

![title](hw_img/hw1.0.jpg)
![title](hw_img/hw1.2.jpg)
![title](hw_img/hw1.3.jpg)

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
np.random.seed(1)
x = np.linspace(-1,1,100)
signal = 2 + x + 2 * x * x
noise = np.random.normal(0, 0.2, 100)
y = signal + noise

#####################################

xtrain = x[0:80]
ytrain = y[0:80]

one = np.ones([80,1])

xtrain2 = np.square(xtrain)
xtrain3 = np.power(xtrain, 3)
h=np.column_stack((one,xtrain,xtrain2))
print(h)

h_trans = h.transpose()

temp = np.dot(h_trans, h)

inverse = np.linalg.inv(temp)
temp2 =np.dot(h_trans,ytrain)

A = np.dot(inverse,temp2)

print(A)

f_train=np.dot(h,A)
print(f_train)


least_square = ytrain - f_train
least_square_transpose = least_square.transpose()

np.dot(least_square_transpose, least_square)
error = np.sqrt(np.sum(np.dot(least_square_transpose, least_square)))
print(error)


[[ 1.00000000e+00 -1.00000000e+00  1.00000000e+00]
 [ 1.00000000e+00 -9.79797980e-01  9.60004081e-01]
 [ 1.00000000e+00 -9.59595960e-01  9.20824406e-01]
 [ 1.00000000e+00 -9.39393939e-01  8.82460973e-01]
 [ 1.00000000e+00 -9.19191919e-01  8.44913784e-01]
 [ 1.00000000e+00 -8.98989899e-01  8.08182838e-01]
 [ 1.00000000e+00 -8.78787879e-01  7.72268136e-01]
 [ 1.00000000e+00 -8.58585859e-01  7.37169677e-01]
 [ 1.00000000e+00 -8.38383838e-01  7.02887460e-01]
 [ 1.00000000e+00 -8.18181818e-01  6.69421488e-01]
 [ 1.00000000e+00 -7.97979798e-01  6.36771758e-01]
 [ 1.00000000e+00 -7.77777778e-01  6.04938272e-01]
 [ 1.00000000e+00 -7.57575758e-01  5.73921028e-01]
 [ 1.00000000e+00 -7.37373737e-01  5.43720029e-01]
 [ 1.00000000e+00 -7.17171717e-01  5.14335272e-01]
 [ 1.00000000e+00 -6.96969697e-01  4.85766758e-01]
 [ 1.00000000e+00 -6.76767677e-01  4.58014488e-01]
 [ 1.00000000e+00 -6.56565657e-01  4.31078461e-01]
 [ 1.00000000e+00 -6.36363636e-01  4.04958678e-01]
 [ 1.00000000e+00 -6.16161616e-

### HW2

In [4]:
x_pre = x[80:]
y_pre = y[80:]

one_test = np.ones([20,1])

xtest2 = np.square(x_pre)

h_test = np.column_stack((one_test, x_pre, xtest2))
print(h_test)

print(A)
f_test = np.dot(h_test,A)
print(f_test)


least_square_test = y_pre - f_test

error_test = np.sqrt(np.sum(np.dot(least_square_test.transpose(), least_square_test)))

print(error_test)

[[1.         0.61616162 0.37965514]
 [1.         0.63636364 0.40495868]
 [1.         0.65656566 0.43107846]
 [1.         0.67676768 0.45801449]
 [1.         0.6969697  0.48576676]
 [1.         0.71717172 0.51433527]
 [1.         0.73737374 0.54372003]
 [1.         0.75757576 0.57392103]
 [1.         0.77777778 0.60493827]
 [1.         0.7979798  0.63677176]
 [1.         0.81818182 0.66942149]
 [1.         0.83838384 0.70288746]
 [1.         0.85858586 0.73716968]
 [1.         0.87878788 0.77226814]
 [1.         0.8989899  0.80818284]
 [1.         0.91919192 0.84491378]
 [1.         0.93939394 0.88246097]
 [1.         0.95959596 0.92082441]
 [1.         0.97979798 0.96000408]
 [1.         1.         1.        ]]
[2.02361633 1.04867261 1.98497911]
[3.42337566 3.49478797 3.5678205  3.64247325 3.71874624 3.79663944
 3.87615288 3.95728654 4.04004042 4.12441453 4.21040887 4.29802343
 4.38725822 4.47811323 4.57058847 4.66468394 4.76039963 4.85773555
 4.95669169 5.05726806]
0.4785764798994469
