In [1]:
import numpy as np
import matplotlib.pyplot as plt
np.random.seed(1)

In [2]:
# three kinds of activation functions
def fun(x, dev):
    if dev == 'sigmoid':
        return 1 / (1 + np.exp(-x))
    elif dev == 'tanh':
        return np.tanh(x)
    elif dev == 'relu':
        return x if x >= 0 else 0

# differential of fun
def dfun(x, dev):
    if dev == 'sigmoid':
        fx = fun(x, 'sigmoid')
        return fx * (1 - fx)
    elif dev == 'tanh':
        return 1 - np.tanh(x) ** 2
    elif dev == 'relu':
        return 1 if x >= 0 else 0

In [3]:
mp1=100 # 100 lines
np1=30 # each line with 30 points
noise1 = (2.0 * np.random.random((mp1,np1)) - 1) * 0.1
X_train1=np.ones((mp1,np1)) + noise1
print(X_train1)

help(np.random.random)

[[0.9834044  1.0440649  0.90002287 ... 0.90781096 0.93396608 1.0756285 ]
 [0.91966937 0.98422153 1.09157791 ... 0.92934571 1.01786111 1.03995167]
 [0.92046689 0.9828112  1.03888003 ... 1.09296801 1.0326883  1.02433914]
 ...
 [0.94520883 0.90022297 1.03714331 ... 1.0066807  1.09264831 1.0518108 ]
 [0.96510806 0.91716986 1.0072048  ... 1.0683796  1.02778956 1.01312629]
 [0.96142842 1.07535541 1.09776438 ... 0.98790782 0.93369539 1.00581744]]
Help on built-in function random:

random(...) method of numpy.random.mtrand.RandomState instance
    random(size=None)
    
    Return random floats in the half-open interval [0.0, 1.0). Alias for
    `random_sample` to ease forward-porting to the new random API.



In [4]:
mp1 = 100
np1 = 30
noise1 = (2.0 * np.random.random((mp1, np1)) - 1) * 0.1
X_train1 = np.ones((mp1, np1)) + noise1

X_train2 = np.ones((mp1, np1))
for row in X_train2:
    randnum = int(np.random.random(1) * 25 + 1) # the key point : )
    row[randnum] = 0.1
    row[randnum + 1] = 0.1
    row[randnum + 2] = 0.1

print(randnum)

X_train2 = X_train2 + noise1
print(X_train2)

# add dimension with respect to rows
Y_train1 = np.zeros(mp1)[:, np.newaxis]
Y_train2 = np.ones(mp1)[:, np.newaxis]

X_train = np.concatenate((X_train1, X_train2), axis=0)
Y_train = np.concatenate((Y_train1, Y_train2), axis=0)

w = (2 * np.random.random((np1,1)) - 1) * 0.25
b = (2 * np.random.random(1) - 1) * 0.25

24
[[1.05869693 0.90717583 0.93827178 ... 0.93604671 1.08771013 1.09415003]
 [0.96089705 1.07249728 1.06843582 ... 0.95538461 1.06895227 0.98332383]
 [1.0001968  1.04592468 0.95174434 ... 0.97601424 0.93526761 0.98376703]
 ...
 [1.07602399 0.98766342 1.01726596 ... 0.91504653 0.9233188  1.08276081]
 [1.07395428 0.95839049 0.92039999 ... 0.94419909 1.04724729 1.01697473]
 [1.00510722 1.0322889  1.02641352 ... 0.9052382  1.0901656  1.01398353]]


In [5]:
X1 = fun(np.dot(X_train, w) + b, 'sigmoid')
error1 = np.sqrt(np.dot((Y_train - X1).T, Y_train - X1))
error1

array([[7.36525856]])

In [6]:
epochs = 5000
eta = 0.1
X0 = np.copy(X_train)
b0 = np.copy(b)
w0 = np.copy(w)

error_array = []
epochs_array = list(range(5000))

for k in range(epochs):
    X1 = fun(np.dot(X0, w0) + b0, 'sigmoid')
    X1_error = X1 - Y_train
    X1_delta = X1_error * dfun(X1, 'sigmoid')
    
    #update weights
    w0 = w0 - eta * np.dot(X0.T, X1_delta)
    c = np.ones(len(X1_delta))
    b0 = b0 - eta * np.dot(c, X1_delta)
    
    error = np.sqrt((np.dot((Y_train - X1).T, Y_train - X1)) / len(X1))
    error_array.append(error[0][0])

print('error = ')
print(error)

error = 
[[0.05501589]]


In [7]:
test1=np.ones(np1)

print("Output test Training:", test1)

print("Output results:")

X1=fun(np.dot(test1,w0)+b0, 'sigmoid')

print("Predict= ",X1)

test1[5]=0.1

print("Output test Training:" ,test1)

X1=fun(np.dot(test1,w0)+b0, 'sigmoid')

print("Output results Predict=:",X1)

Output test Training: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1.]
Output results:
Predict=  [5.51554984e-06]
Output test Training: [1.  1.  1.  1.  1.  0.1 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1. ]
Output results Predict=: [0.02100317]
